input_dir: ../BestStarApp/Resources/
output_dir: ../BestStarApp/Resources/Generated/

strings:
  inputs: String/Localizable.strings
  outputs:
    templateName: structured-swift4
    output: Strings.swift

xcassets:
  inputs: Assets.xcassets
  outputs:
    templateName: swift4
    output: Assets.swift

colors:
  inputs: Colors/Colors.json
  outputs:
    templateName: swift4
    output: Colors.swift

fonts:
  inputs: Fonts
  outputs:
    templateName: swift4
    output: Fonts.swift
